spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234!
    url: jdbc:mysql://localhost/customers
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  server:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true